### ISSUE TITLE
workshop?

### ISSUE THREAD

**Issue by tcurdt** [AK-Homberger/NMEA2000-Workshop#1]
Wo wäre denn der Workshop? Es sind nirgendwo Kontakt Infos zu finden.

**Comment by AK-Homberger** [comment]
Hallo,

Der Workshop war am 30. Januar. 
Aufgrund des Zeitbedarfs planen wir aber den Workshop in zwei Teile aufzuteilen. Acht Stunden Online-Workshop waren einfach zu viel. 

Organisation geht dann über diesen Link: https://app1.edoobox.com/Y-T-S/Yachtelektrik/Seminar.ed.512603?edref=Y-T-S

Mit etwas Vorkenntnissen im Programmieren und Elektronik kann man den Workshop aber auch in eigener Regie machen. Alle Informationen sind im Text vorhanden. Ohne Vorkenntnisse wird das aber eventuell schwierig, weil bei Problemen keine direkte Hilfe erfolgen kann.

Viele Grüße
Andreas

**Comment by tcurdt** [comment]
Hallo Andreas,

Danke für die schnelle Antwort!
Genügend Vorkenntnisse sind eigentlich vorhanden. Nachbau sollte nicht so das Problems ein. Aber der Austausch wäre interessant gewesen wenn es um weitere Details geht.

Dieser Link funktioniert übrigens nicht:

https://app1.edoobox.com/de/Y-T-S/Yachtelektrik%20%26%20Elektro-Refit/Online-Kurs.ed.552123/?edref=Y-T-S

Gruss,
Torsten

**Comment by AK-Homberger** [comment]
Hallo Torsten,

wir planen gerade einen weiteren Workshop im Open Boat Project live Format.
Du kannst da gern mitmachen.

https://www.segeln-forum.de/board194-boot-technik/board195-open-boat-projects-org/78918-open-boat-projects-live-3/?s=c8766c7bea94061aa3d0a8ebb954e6c4d6c9e1ec

Viele Grüße
Andreas

**Comment by tcurdt** [comment]
Nach der letzten Doodle Umfrage hab ich dann leider auch nie wieder was gehört. Gab es dann noch eine Veranstaltung im März?

Dein edoobox funktioniert übrigens immer noch nicht richtig. 

![Screen Shot 2021-03-11 at 10 39 14](https://user-images.githubusercontent.com/13697/110767000-0fdef380-8256-11eb-95f4-3ace6c7a2f49.png)
