### ISSUE TITLE
NMEA2000 CAN-Module für die ESP32

### ISSUE THREAD

**Issue by hwater** [AK-Homberger/NMEA2000-Workshop#2]
Vorsichtig bei den Modulen:

Alle meine Module haben einen eingelöteten Terminatorwiderstand von 120 Ohm am Board.
Das klappt bei den Breadboard mit 2 Schaltungen - dann ist zwischen H & L genau 60 Ohm, aber falls mehrere
in einen bestehenden Bus integriert werden sollen, immer darauf achten vorher die SMD Widerstände auszulöten.
Da dort nur 2 Widerstände drauf sind, kann man diese leicht durchmessen um den richtigen zu finden.

Auch auf den Raspberry CAN-Adaptern sind übrigens die Terminator-Widerstände mit aktiv, auch hier darauf achten.

Wie schon vom Autor erwähnt, sollte der korrekte Widerstand der H und L Leitungen ca. 60 Ohm betragen.

Vielen Dank für den Kurs, bin gerade dabei den BME680 zu integrieren, klappt auch für Druck und Temperatur - aber ich komme mit der Übersetzung Luftfeuchte und Gasmessung zu NMEA2000 noch nicht klar. Vielleicht hat da schon wer etwas gecodet.

Mit freundlichen Grüßen
Holger Watermann / Donau

**Comment by AK-Homberger** [comment]
Das manche CAN-Transceiver einen Widerstand mit verbaut haben, wurde auch schon im Segeln-Forum berichtet. Die Module von Eckstein sind aber OK. Zumindest die Komponenten, die ich erhalten hatte. Manche Transceiver sind wohl auch was das Signal angeht empfindlich. Ich werde zur Sicherheit noch einen Hinweis im Workshop mit aufnehmen.

Luftfeuchtigkeit ist doch im Workshop direkt enthalten. Für Gaskonzentration gibt es meines Wissens kein standardisiertes PGN.

**Comment by hwater** [comment]
Ja, die Feuchtigkeit hab ich gefunden. Danke - dann können wir das Issure schliessen.

Holger
