### ISSUE TITLE
multiple ds18b20

### ISSUE THREAD

**Issue by sprokkie** [AK-Homberger/NMEA2000-Workshop#7]
Hi I want to use multiple ds18B20 connected to one esp32 and sens the values to the n2k network.
I cannot find the adressing in the workshop software for the ds18b20.

can you explain where i can find them or how to add them?

regards,
Sprokkie

**Comment by AK-Homberger** [comment]
This topic is not covered in the workshop. But you can find the solution in my NMEA2000 WLAN Gateway code (My Boat Edition).

https://github.com/AK-Homberger/NMEA2000-Gateway-My-Boat-Edition
